set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backup
set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_CACHE_HOME/vim/viminfo | endif

set fenc=utf-8
set autoread
set hidden
set ambiwidth=double

" editor config.
set virtualedit=onemore
set backspace=indent,eol,start
set smartindent
set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set history=10000
set clipboard+=unnamed
inoremap <silent> jj <ESC>

" visual config.
syntax on
set title
set number
set ruler
set cursorline
set scrolloff=8
set showcmd
set showmatch
set matchtime=1
set laststatus=2
set wildmode=list:longest
set list
set listchars=tab:▸-,trail:･,nbsp:%,eol:↵,extends:❯,precedes:❮
set pumheight=10
set display=lastline

" search config.
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch

" vim-plug config
call plug#begin("$XDG_DATA_HOME/vim/plugged")
Plug 'airblade/vim-gitgutter'
Plug 'cohama/lexima.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
call plug#end()

" NERDTree config
nnoremap <silent><C-e> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
